# Generated by Django 3.1.13 on 2021-07-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
