# Generated by Django 3.1.13 on 2021-07-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210719_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title')},
        ),
    ]
